regex:
  time:
    1: '[0-9]{0,2}[:]?[0-9]{1,2}[.][0-9]{2}'  # 01:35.22
    2: '[0-9]{1}:[0-9]{2}\,[0-9]{2}'         # 1:35,22
    3: '(?<!X)(?<=\s)([0-9]:)?[0-9]{2}[\.\,][0-9]{2}'          # no X, space, 1:35.22 | 35.22 | 35,22 | 1:35,22
    4: '[0-9]{0,2}[:]?[0-9]{1,2}[:][0-9]{2}'  # 01:35:22
    5: '(?!99:99,99)[0-9]{2}:[0-9]{2}\,[0-9]{2}'         # 01:35,22
    6: '(?<=\s)([0-9]:)?[0-9]{2}\.[0-9]{2}'   # 1:35.22
    7: '([0-9]'')?[0-9]{2}\.[0-9]{2}'
    8: '[0-9]{1}:[0-9]{2}\,[0-9]{2}'         # 1:35,22
    9: '[0-9]{1}''[0-9]{2}""[0-9]{2}'         # 1'35""22
    10: '(?<!X)([0-9]:)?[0-9]{2}\.[0-9]{2}'          # no X, 1:35.22 | 35.22
  name:
    1: >
        /([A-z\x{00C0}-\x{02A0}\x{0390}-\x{0520}\-\'\’\.]{1,}[ ]?)+(,\s?)([A-z\x{00C0}-\x{02A0}\x{0390}-\x{0520}\-\'\’\.]{1,}[ ]?(?!DQ)(?!XDQ))/u
    2: >
        /([A-z\x{00C0}-\x{02A0}\x{0390}-\x{0520}])([A-z\x{00C0}-\x{02A0}\x{0390}-\x{0520}\-\'\’\.]\s?)+/u
    3: >
        /(?!.*DSQ|DIS|DNS|dis)\b([A-z\x{00C0}-\x{02A0}\x{0390}-\x{0520}])([A-z\x{00C0}-\x{02A0}\x{0390}-\x{0520}\-\'\’\.] ?)+/u
    4: >
        /(?<=\s)(([A-z\x{00C0}-\x{02A0}\x{0390}-\x{0520}\-\'\’]+[ ]?)+(,?[ ]?))+/u
    5: >
        /(?!.*DSQ|DIS|DNS|dis)\b([A-z\x{00C0}-\x{02A0}\x{0390}-\x{0520}\-\'\’\.]{2,}\s?)+(,\s?)([A-z\x{00C0}-\x{02A0}\x{0390}-\x{0520}\-\'\’\.]{2,}\s?(?!DQ)(?!XDQ))/u
    6: >
        /([A-z\x{00C0}-\x{02A0}\x{0390}-\x{0520}\-\'\’\.]\s?)+,\s([A-z\x{00C0}-\x{02A0}\x{0390}-\x{0520}\-\'\’\.]{1,}\s?)/u
  first_name:
    1: >
      /\b([A-Z]([a-z\s]+))+/u
  last_name:
    1: >
      /([A-Z]'?\s?)+\b(?=[^\-])/u
  yob:
    1: '/\s[0-9]{2}\s/'         # 96
    2: '/\s[0-9]{4}\s/'         # 1996
    3: '/[0-9],[0-9]{3}/'   # 1,996
    4: '/\s(?!0.000)[0-9]\.[0-9]{3}\s/'   # 1.996
    5: '/(?<=[A-Z])[0-9]{2}(?=[A-Z])/'         # 96
    6: '/(?<=\()[0-9]{4}(?=\))/'        # (1996)
    7: '/(?<=\,)[0-9]{4}(?=\,)/'        # ,1996,
event_signifiers: # if a line contains one of these, the line should contain an event
  - 'Programmanr'
  - 'Event'
  - 'over all heats Finale'
  - 'heat by heat'
  - 'Ergebnisse'
event_designifiers: # if a line contains one of these, the line shouldn't contain an event
  - 'DISKWALIFICATIE CODES'
  - 'Leaving the water after an event before permission is given by the official.'
  - 'Not completing the event in accordance with the event description or general rules.'
  - 'Did not compete in all events ‐ not eligible for overall pointscore awards'
  - 'Team Rankings'
  - 'Age Name Team Finals Time'
  - 'Name TeamFinals Time'
  - 'relevos'
event_rejectors: # if a line contains one of these, the complete event should be ignored
  - 'Relay'
  - 'Team'
  - 'LC Meter Brick Carry'
  - '35 LC Meter Manikin Carry'
  - 'Line Throw'
  - 'Linethrow'
  - 'Relais'
  - 'Staffetta'
  - 'brick'
  - '50 LC Meter rescue medley'
  - '50m Rescue Medley'
  - '4x'
  - '35 LC Metre'
event_stopper: # if a line contains one of these, the current event should be completed and following results are not added
  - 'Open Age Group - Full Results'
round_signifiers:
  - 'Final'
round_designifiers:
  - 'round designifier'
dq_signifiers:
  - 'DQ'
  - '10:00.00'
  - '5:00.00'
  - 'DNF'
  - 'DSQ'
  - 'Forfait'
  - '00:00,00'
  - 'DISQ'
  - 'Squalif'
  - '00:00.00'
dq_times:
  - '88:88,88'
  - '59:59.99'
  - '88:88:88'
  - '00:00.00'
dns_signifiers:
  - 'DNS'
  - 'n.a.'
  - 'd.n.s.'
result_rejectors: # if a line contains one of these, the result should be ignored
  - 'Splash Meet Manager'
  - 'Record'
  - 'Australian:'
  - 'World:'
  - 'rekord'
  - 'NR:'
  - 'CR:'
  - 'NR ('
  - 'CR ('
  - 'NR('
  - 'CR('
  - 'WR:'
  - 'WR :'
  - 'National:'
  - 'Championship:'
genders:
  male_signifiers:
    - 'Men'
    - 'Heren'
    - 'Boys'
    - 'Jongens'
    - 'Masculino'
    - 'Male'
    - 'Messieurs'
    - 'Homme'
    - 'Home'
    - 'Maschile'
    - 'männlich'
    - 'Maschi'
    - 'Mens'
  female_signifiers:
    - 'Women'
    - 'Dames'
    - 'Girls'
    - 'Meisjes'
    - 'Femenino'
    - 'Female'
    - 'Dame'
    - 'Femminile'
    - 'weiblich'
    - 'Femmine'
    - 'Womens'
disciplines:
  1:
    - '100m manikin carry with fins'
    - '100m Manikin Carry with Fins'
    - '100m popduiken met zwemvliezen'
    - '100 m. remolque de maniquí'
    - '100m manikin (ring) carry with fins'
    - '100 m Manikin Carry with Fins'
    - '100m mannequin palmes'
    - '100 manikin carry with fins'
    - 'A2-Popredden met vinnen'
    - '100m Popredden met vinnen'
    - '100 LC Metre Fins Manikin Carry'
    - '100 LC Meter Manikin Rescue'
    - '100 LC Meter Manikin Carr'
    - '100 LC Meter manikin carry'
    - '100 LC Meter Manikin Carry'
    - 'Manikin Carry w/Fins'
    - '100 Meter manikin  carry+fins'
    - '100 Meter manikin carry+fins'
    - '100 LC Meter Manakin Carry (Fins)'
    - '100m Manikin Carry'
    - 'Manikin Carry with Fins (100 m)'
    - '100 M Manikin Carr'
    - '100 m Mannequin Palmes'
    - '100 Mannequin Palme'
    - 'mai 2013 Finale Mannequin Palme'
    - '100 m Mani	qui Aletas'
    - 'Manichino pinne mt.100'
    - '100 LC Meter Open Manikin C w F'
    - '100 LC Meter Mankin Carry W/Fins'
    - '100 LC Meter ManikinCarryW/fins'
    - '100 LC Meter OpenManikinCarry/fin'
    - '100 LC Metre Carry'
    - '100 LC Metre 100 Carry'
    - '100 LC Meter Freestyle ManikinCarryW/Fins'
    - '100 LC Meter manikin with fins'
    - '100 LC Meter Manik Carry Fins'
    - '100m Manichino pinne'
    - '100 Meter Manikin Carry w.Fins'
    - '100 Meter Manikin Carry w Fins'
    - '100m ratowanie manekina w płetwach'
    - '100m ratowanie w płetwach'
    - '100 m ratowanie manekina w płetwach'
    - '100m dukke'
    - '100m Retten mit Flossen'
    - '100m Retten einer Puppe mit Flossen'
    - '100 m Maniqui Aletas'
    - '100 LC Meter Carry with Fins'
    - '100m Remolque de maniquí con alettas'
    - '100m Remolque de maniquí con aletas'
  2:
    - '50m manikin carry'
    - '50m Manikin Carry'
    - '50m popduiken'
    - '50 m. remolque de maniquí'
    - '50m Mannequin'
    - '50 manikin carry'
    - 'A4-Popredden'
    - '50m Popredden'
    - '50 LC Metre Manikin Carry'
    - '50 LC Meter Manikin Rescue'
    - '50 LC Meter Manikin Carr'
    - '50 LC Meter mankin carry'
    - '50 Meter mankin carry'
    - '50 LC Meter Manakin Carry'
    - '50m Manikin Carry'
    - '50 M Manikin Carry'
    - 'Manikin Carry (50 m)'
    - '50 M Manikin Carr'
    - '50 m Mannequin'
    - '50 M Mannequin'
    - '50 Mannequin'
    - '50 m Arrastre Mani'
    - 'Trasporto manichino'
    - '50 LC Meter OpenManikinCarryNF'
    - '50 LC Meter ManikinCarryNo Fins'
    - '50 LC Meter ManikinCarryW/O Fins'
    - '50 LC Meter Open ManikinCarry'
    - '50 LC Meter ManikinCarry'
    - '50m Manikin Carr'
    - '50 LC Metre Carry'
    - '50 LC Metre 50 Carry'
    - '50 LC Meter Manik Carry NoFins'
    - '50 LC Meter manikin no  fins'
    - '50 LC Meter manikin no fins'
    - '50 LC Meter manikin, no fins'
    - '50 m. manikin carry'
    - '50 Meter Manikin Carry'
    - '50 LC Metre Mankin Carry'
    - '50m ratowanie manekina'
    - '50m holowanie manekina'
    - '50 m ratowanie manekina'
    - '50m Dukke'
    - '50m Retten'
    - '50m Remolque Maniquí '
  3:
    - '200m obstacle swim'
    - '200m Obstacle Swim'
    - '200m hinderniszwemmen'
    - '200 m. natación con obstáculos'
    - '200m obstacle race'
    - '200 m Obstacle Swim'
    - '200m Obstacles'
    - 'A1-Hinderniszwemmen'
    - '200 LC Metre Obstacle'
    - '200 LC Metre Masters Obstacle'
    - '200 LC Meter Obstacle'
    - '200 LC Meter Obstacles'
    - '200 LC Meter 0bstacles'
    - '200 Meter Obstacle'
    - '200 m. natación con obstáculos'
    - '200 Obstacle Swim'
    - '200 m SWIMMING WITH OBSTACLES'
    - '200 m Obstacles'
    - '200 Obstacle'
    - '200 m Obstaculos'
    - 'Nuoto ostacoli mt.200'
    - '200 Swim with Obstacles'
    - '200 LC Meter NZ Indiv Obstacle'
    - '200 LC Meter Open Swim with Obs'
    - '200 LC Meter Swim with Obstacles'
    - '200 LC Meter Open Swim w Obs'
    - '200 LC Meter 200m Swim w Obs'
    - '200 LC Meter OpenSwim W Obst'
    - '200 LC Meter Swim W Obstacles'
    - '200 LC Meter OpenSwimW/Obstacles'
    - '200m Obstacle'
    - '200 LC Meter Freestyle Swim with Obstacles'
    - '200 LC Meter with obstacles'
    - '200m Swim with Obstacles'
    - '200m Nuoto con ostacoli'
    - '200 m. obstacles'
    - '200m z przeszkodami'
    - '200m Obstcle'
    - '200m Forhindring'
    - '200m Hindernisschwimmen'
    - '200m Natación Obstáculos'
  4:
    - '100m manikin tow with fins'
    - '100m lifesaver'
    - '100 m. socorrista'
    - '100 m Manikin Tow with Fins'
    - '100 manikin tow with fins'
    - '100m Manikin Tow with Fins'
    - 'A5-Lifesaver'
    - '100 LC Metre Fins Manikin Tow'
    - '100 LC Meter Manikin Tow'
    - '100 LC Meter Manikin Tow'
    - '100 LC Meter Manikin Tow'
    - '100 Meter manikin  tow  +fins'
    - '100 Meter manikin  tow+fins'
    - '100 Meter manikin tow +fins'
    - '100 Meter manikin tow+fins'
    - '100 LC Meter Manakin Tow (Fins)'
    - '100 m. socorrista / manikin tube with fins'
    - '100m Manikin Tow w. Fins'
    - '100m Manikin Tow'
    - 'Manikin Tow with Fins (100 m)'
    - '100 m Bouée Tube'
    - '100 Bouée Tube'
    - '100 m Socorrista'
    - 'Manichino pinne e torpedo '
    - '100 Manikin Tow Fins'
    - '100 LC Meter MastersManikinTwF'
    - '100 LC Meter Open Manikin TFins'
    - '100 LC Meter Open ManikinT Fins'
    - '100 LC Meter Open Manikin Tow'
    - '100 LC Meter MastersmaikinTow'
    - '100 LC Meter MasterManikinTow/Fin'
    - '100 LC Meter OpenManikinTowW/Fins'
    - '100 LC Metre Tow'
    - '100 LC Metre 100 Tow'
    - '100 LC Meter Freestyle Manikin Tow W/Fins'
    - '100 LC Meter Masters Manikin Tow'
    - '100m Manich pinne torpedo'
    - '100m Man. pinne torpedo'
    - '100m . tube with fins '
    - '100 m. manikin tube with fins'
    - '100 Meter Manikin Tow w/ Fins'
    - '100 Meter Manikin Tow w Fins'
    - '100 LC Metre Manikin Tow w/ Fins'
    - '100m ratowanie manekina z pasem'
    - '100m ratowanie z pasem'
    - '100m ratownik'
    - '100 m ratownik'
    - '100m redning RTP'
    - '100m Retten mit Flossen und Gurtretter'
    - '100 LC Meter Tow with Fins'
    - '100m Socorrista'
  5:
    - '100m rescue medley'
    - '100m Rescue Medley'
    - '100m reddingswisselslag'
    - '100 m. combinada de salvamento'
    - '100 m Rescue Medley'
    - '100m Combiné'
    - 'A3-Reddingscombiné'
    - '100m Reddingscombiné'
    - '100 LC Metre Rescue Medley'
    - '100 LC Meter Rescue Medley'
    - '100 LC Meter Rescue Medle'
    - '100 LC Meter Rescue Medley'
    - '100 LC Meter LIFESAVING MEDLEY'
    - '100m Rescuemedley'
    - '100 Rescue medley'
    - '100m Medley'
    - 'Rescue Medley (100 m)'
    - '100 M Rescue Medle'
    - '100 m Combiné'
    - '100 Combiné'
    - '100 m Combinada'
    - 'Percorso misto mt.100'
    - '100 LC Meter Open Rescue Medley'
    - '100 LC Meter RescueMedleyManikin'
    - '100 LC Meter IM'
    - '100 LC Metre Rescue Med'
    - '100 LC Meter Freestyle Rescue Medley'
    - '100m Percorso misto'
    - '100 m. medley'
    - '100 Meter Rescue Medley'
    - '100 LC Meter U15 Rescue Medley'
    - '100m ratowanie kombinowane'
    - '100 m ratowanie kombinowane'
    - '100m redningsmedley'
    - 'Red-medley'
    - '100m  Rescue Medley'
    - 'Rescue Medley'
    - '100m Kombinierte Rettungsübung'
    - '100m Combinada de Salvamento'
    - '100m Combinada Salvamento'
  6:
    - '200m Super Lifesaver'
    - '200m superlifesaver'
    - '200 m. supersocorrista'
    - '200m super lifesaver'
    - '200 m Super Lifesaver'
    - 'A6-Super Lifesaver'
    - '200 LC Metre Super Lifesaver'
    - '200 LC Meter Super Lifesaver'
    - '200 LC Meter Su'
    - '200 Meter superlifesaver'
    - 'LC Meter Super Life Saver Individual'
    - '200 SLS'
    - '200m Pool Lifesaver'
    - 'Super Lifesaver (200 m) '
    - '200 meter super lifesaver'
    - '200 M Su'
    - '200 m S.L.S.'
    - '200 Super Sauveteur'
    - 'Super lifesaver'
    - '200 LC Meter Open Super Lifsaver'
    - 'Open 200m Super'
    - '200 LC Metre Superlifesaver'
    - '200 m. superlifesaver'
    - '200 m. súper socorrista'
    - '200m super ratownik'
    - '200m super'
    - 'Super  Lifesaver'
    - '200m Super-Lifesaver'
    - '200m Súper socorrista'
  7:
    - '50 m obstacle swim'
    - '50m Obstacle Swim'
    - '50 Swim with Obstacles'
    - '50 LC Meter Swim with Obstacles'
    - '50 LC Meter 50m Swim w Obstacles'
    - '50 LC Meter Swim W Obstacles'
    - '50 LC Meter Freestyle Swim with Obstacles'
    - '50 LC Meter with obstacles'
    - '50m Swim with Obstacles'
    - '50m Nuoto con ostacoli '
  8:
    - '50 m free style'
    - '50m vrije slag'
    - 'Open 50m Freestyle'
    - '50 LC Meter Swim'
  9:
    - '50 m freestyle with fins'
    - '50m Freestyle with Fins'
    - '50 LC Meter Swim with Fins'
    - '50 Swim with Fins'
    - '50 LC Meter MastersSwimWFins'
    - '50 LC Meter Open Swim with Fins'
    - '50 LC Meter MastersSwim W Fins'
    - '50 LC Meter Freestyle Masters With Fins'
    - '50 LC Meter Freestyle Swim with Fins'
    - '50 LC Meter Masters With Fins'
    - '50 LC Meter Masters Swim,Fins'
    - '50 LC Meter Free with fins'
    - '50m Swim with Fins'
    - '50 LC Meter Freestyle with Fins'
    - '50 LC Metre Swim with Fins'
    - '50 LC Metre Freestyle with Fins'
  10:
    - '50m Manikin Carry (relay leg 3)'
    - '50m popvervoeren (start met pop)'
  11:
    - '50 m slepen torpedo en drenkeling'
  12:
    - '25 m pop'
    - '25m Manikin Carry'
    - '25m pop'
  13:
    - '50 m vrij met torpedo'
    - '50m torpedoboei'
    - '50 m freestyle towing a rescue tube'
  14:
    - '50 m pop met vliezen'
    - '50m Manikin Carry with Fins (relay leg 4)'
    - '50 m pop  met vliezen'
  18:
    - '100m Obstacle Swim'
    - '100 Meter Obstacle'
    - '100 LC Meter Obstacle'
    - '100 LC Meter Obstacles'
    - '100m Obstacle'
    - '100 Obstacle Swim'
    - '100m Obstacles'
    - '100 m. natación con obstáculos / 100 m. obstacles'
    - 'A1-100m Hinderniszwemmen/Obstacles'
    - 'Nuoto ostacoli mt.100'
    - '100 Swim with Obstacles'
    - '100 LC Meter Swim with Obstacles'
    - '100 LC Meter MasterSwimW/Obstacle'
    - '100 LC Meter Masters Swm w Obs'
    - '100 LC Meter 100m Swim w Obs'
    - '100 LC Meter 100 Swim w Obs'
    - '100 LC Meter MastersSwim W Obst'
    - '100 LC Meter Swim W Obstacles'
    - '100 LC Meter MastersSwimWObstacle'
    - '100 LC Meter MastersSwimObstacle'
    - '100 LC Metre Obstacles'
    - '100 LC Metre 100 Obstacles'
    - '100 LC Meter Freestyle Swim with Obstacles'
    - '100 LC Meter Freestyle MasterSwimW/Obstacle'
    - '100 LC Meter Masters Obstacles'
    - '100 LC Meter with obstacles'
    - '100m Swim with Obstacles'
    - '100 LC Metre Obstacle'
    - '100 LC Metre Masters Obstacle'
    - '100m z przeszkodami'
    - '100 m. natación con obstáculos'
    - '100 M Obstacle Swim'